name: Deploy Terraform Engine
on:
  workflow_dispatch:  # Manual trigger
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'eu-west-1'
      stack-name:
        description: 'SAM Stack Name'
        required: true
        default: 'SAM-TRE'
      s3-bucket:
        description: 'S3 Bucket for SAM artifacts'
        required: true
      team:
        type: choice
        description: Team name for environment config
        default: edp
        options:
          - edp
      environment:
        type: choice
        description: Environment name for environment config
        default: dev
        options:
          - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Setup Go 1.21
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::913524929808:role/ccoe-ecp-github-execution-edp-foundation-layer
        aws-region: ${{ inputs.region }}
    
    - name: Setup SAM CLI
      uses: aws-actions/setup-sam@v2
    
    - name: SAM Build
      run: sam build

    - name: SAM Deploy
      run: |
        sam deploy \
          --stack-name ${{ inputs.stack-name }} \
          --region ${{ inputs.region }} \
          --s3-bucket ${{ inputs.s3-bucket }} \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
